module.exports = (grunt) ->
  pkg = grunt.file.readJSON 'package.json'
  grunt.initConfig
    watch:
      files: ['coffee/**/*.coffee'],
      tasks: ['coffee', 'concat', 'uglify', 'copy']

    coffee:
      compile:
        options:
            bare: true,
            separator: 'linefeed'
          sourceMap: true
        files: [
            expand: true,
            cwd: 'coffee/',
            src: ['**/*.coffee'],
            dest: 'js/',
            ext: '.js'
        ]

    concat:
      options:
        banner: "/* this file is generated by concat task of grunt.js */\n"
      dist:
        src: ['js/hydranger/**/*.js']
        dest: 'js/hydranger.js'

    uglify:
      dist:
        src: "<%= concat.dist.dest %>",
        dest: "compress/hydranger.min.js"

    jshint:
      options:
        jshintrc: '.jshintrc'
      all: ["<%= concat.dist.src %>"]

    copy:
      files:
        src: ["<%= concat.dist.dest %>"]
        dest: '../public/common/js/hydranger.js'


  grunt.loadNpmTasks 'grunt-contrib-concat'
  grunt.loadNpmTasks 'grunt-contrib-coffee'
  grunt.loadNpmTasks 'grunt-contrib-watch'
  grunt.loadNpmTasks 'grunt-contrib-uglify'
  grunt.loadNpmTasks 'grunt-contrib-jshint'
  grunt.loadNpmTasks 'grunt-contrib-copy'

  grunt.registerTask "js", ["jshint", "concat", "uglify"]
